export const PRODUCT_ADD_REVIEW = 'PRODUCT_ADD_REVIEW';
export const PRODUCT_ADD_TO_CART = 'PRODUCT_ADD_TO_CART'
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE'
export const PRODUCTS_ADD_ALL = 'PRODUCTS_ADD_ALL'
export const PRODUCTS_SEARCH = 'PRODUCTS_SEARCH'
export const PRODUCTS_SET_SYNCED = 'PRODUCTS_SET_SYNCED'
export const SKIP_SET = 'SKIP_SET'